In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [7]:
pd.read_excel("EF2022.xlsx",)

,type,name,name.1,email,handphone
0,Chat,"JIC: Monash & W. Michigan Uni (Australia, Ma...",Hilario Arles Hogan,2013892.hilario@sma.kanisius.sch.id,NaN
1,Chat,"JIC: Monash & W. Michigan Uni (Australia, Ma...",William Wirohusodo,2013911.william@sma.kanisius.sch.id,NaN
2,Chat,"JIC: Monash & W. Michigan Uni (Australia, Ma...",Bonifacius Galih Pramuditho Rennes,2013918.bonifacius@sma.kanisius.sch.id,NaN
3,Chat,"JIC: Monash & W. Michigan Uni (Australia, Ma...",Christian Yudistira Hermawan,2013922.christian@sma.kanisius.sch.id,NaN
4,Chat,"JIC: Monash & W. Michigan Uni (Australia, Ma...",Gamaliel Areteo Pramuditya,2013926.gamaliel@sma.kanisius.sch.id,NaN
...,...,...,...,...,...
9328,Chat,UNPAR,Pascalis Elan Sanjaya,2214697.pascalis@sma.kanisius.sch.id,NaN
9329,Chat,UNPAR,Rafael Russell Effendi,2214699.rafael@sma.kanisius.sch.id,NaN
9330,Chat,UNPAR,Thierry Alexander,2214702.thierry@sma.kanisius.sch.id,NaN
9331,Chat,UNPAR,William Henry Mulya Suwandi,2214703.william@sma.kanisius.sch.id,NaN
9332,Chat,UNPAR,Farrel Javen Sunjoyo,javensunjoyofarrel@gmail.com,085951273357